export { default as Home } from './home/home'
export { default as About } from './about/About'
export { default as Partnership } from './partnership/Partnership'
export { default as Departments } from './departments/Departments'
export { default as Contact } from './contact/Contact'
export { default as Credentials } from './credentials/Credentials'
export { default as Products } from './products/Products'
